eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8070
spring:
  application:
    name: schools
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TestSC;encrypt=true;trustServerCertificate=true;
    hikari:
      username: MyLogin
      password: @dmin2024
  jpa:
    hibernate:
      ddl-auto: create
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

application:
  config:
    students-url: http://localhost:8222/api/v1/students

management:
  tracing:
    sampling:
      probability: 1.0
