eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


server:
  port: 8090
spring:
  application:
    name: students
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;databaseName=TestM;encrypt=true;trustServerCertificate=true;
    hikari:
      username: MyLogin
      password: @dmin2024
  jpa:
    hibernate:
      ddl-auto: create
    database: sql_server
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

management:
  tracing:
    sampling:
      probability: 1.0
